# Generated by Django 4.2.11 on 2025-04-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code_number', models.CharField(blank=True, help_text='Auto-generated unique user code', max_length=20, null=True, unique=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_photos/')),
                ('allergies', models.JSONField(default=list, help_text='List of allergies stored as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
